[build]
  base = "apps/web"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://profitpeek-dashboard-mvp.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
