# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "profitpeek"
client_id = "your_shopify_api_key_here"
application_url = "https://your-frontend-url.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_orders,read_customers,read_inventory,read_analytics"

[auth]
redirect_urls = [
  "https://your-frontend-url.vercel.app/auth/callback",
  "https://your-backend-url.onrender.com/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "your-dev-store.myshopify.com"
